name: Update Branch Strategy

on:
  push:
    branches:
      - '*'  # Run on all branches
    paths-ignore: 
      'README.md'

jobs:
  generate-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Git
      run: |
        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "${{ secrets.NAME }}"

    - name: Generate Git Log
      run: |
        git fetch origin
        git log --all --decorate --oneline --graph > git-log.txt
        echo "::set-output name=log::$(cat git-log.txt)"
        cat git-log.txt
      env:
        LOG_CONTENT: ${{ steps.generate-log.outputs.log }}

    - name: Update README
      id: readme-update
      run: |
        # Replace the content within the "Branch Strategy" section
        sed -i '/# Branch Strategy/ {
            N
            s/\(.*\)\n\(.*\)/# Branch Strategy\n\nHere is the Git log for all branches in the repository:\n\n```\n'"${LOG_CONTENT}"'\n```\n\n# Other Sections/
        }' README.md
      

    - name: Push Changes
      run: |
        git add .
        git commit -m "Automated commit to README.md"
        git push --quiet "https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git" ${{ github.ref }}
